name = "caliber"
compatibility_date = "2025-11-30"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "caliber-db"
database_id = "55a19e36-ed5b-4a31-83db-56ec83dd9a71"
preview_database_id = "55a19e36-ed5b-4a31-83db-56ec83dd9a71"
migrations_dir = "drizzle"

[assets]
directory = "dist/client"
