name = "caliber-corporate"
compatibility_date = "2025-11-30"
compatibility_flags = ["nodejs_compat"]
main = "worker.ts"

[[kv_namespaces]]
binding = "KV"
id = "ab583242d9ba46ab91ae5b7e488dc8c2"

[[d1_databases]]
binding = "DB"
database_name = "apex-db"
database_id = "748c0e4f-002f-4601-a831-4fe05bfd3e2f"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1

[assets]
directory = "dist/client"
