/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SyncRouteImport } from './routes/sync'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LinkedinSearchRouteImport } from './routes/linkedin-search'
import { Route as LinkedinJobsRouteImport } from './routes/linkedin-jobs'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminSetupRouteImport } from './routes/admin-setup'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTestRouteImport } from './routes/api/test'
import { Route as ApiV3StatsRouteImport } from './routes/api/v3/stats'
import { Route as ApiV3LogsRouteImport } from './routes/api/v3/logs'
import { Route as ApiV3JobsRouteImport } from './routes/api/v3/jobs'
import { Route as ApiV3JobContentRouteImport } from './routes/api/v3/job-content'
import { Route as ApiV3CategoriesRouteImport } from './routes/api/v3/categories'
import { Route as ApiJobsSearchRouteImport } from './routes/api/jobs/search'
import { Route as ApiAuthSignOutRouteImport } from './routes/api/auth/sign-out'
import { Route as ApiAuthGetSessionRouteImport } from './routes/api/auth/get-session'
import { Route as ApiAiUnicornRouteImport } from './routes/api/ai/unicorn'
import { Route as ApiAiSearchRouteImport } from './routes/api/ai/search'
import { Route as ApiAiScoreAllRouteImport } from './routes/api/ai/score-all'
import { Route as ApiAiRecommendRouteImport } from './routes/api/ai/recommend'
import { Route as ApiAiMatchRouteImport } from './routes/api/ai/match'
import { Route as ApiAiInsightsRouteImport } from './routes/api/ai/insights'
import { Route as ApiAiGenerateResumeRouteImport } from './routes/api/ai/generate-resume'
import { Route as ApiAdminCleanupNonUsJobsRouteImport } from './routes/api/admin/cleanup-non-us-jobs'
import { Route as ApiV3JobsPruneRouteImport } from './routes/api/v3/jobs/prune'
import { Route as ApiAuthSignUpEmailRouteImport } from './routes/api/auth/sign-up/email'
import { Route as ApiAuthSignInEmailRouteImport } from './routes/api/auth/sign-in/email'

const SyncRoute = SyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkedinSearchRoute = LinkedinSearchRouteImport.update({
  id: '/linkedin-search',
  path: '/linkedin-search',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkedinJobsRoute = LinkedinJobsRouteImport.update({
  id: '/linkedin-jobs',
  path: '/linkedin-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/admin-setup',
  path: '/admin-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestRoute = ApiTestRouteImport.update({
  id: '/api/test',
  path: '/api/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV3StatsRoute = ApiV3StatsRouteImport.update({
  id: '/api/v3/stats',
  path: '/api/v3/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV3LogsRoute = ApiV3LogsRouteImport.update({
  id: '/api/v3/logs',
  path: '/api/v3/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV3JobsRoute = ApiV3JobsRouteImport.update({
  id: '/api/v3/jobs',
  path: '/api/v3/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV3JobContentRoute = ApiV3JobContentRouteImport.update({
  id: '/api/v3/job-content',
  path: '/api/v3/job-content',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV3CategoriesRoute = ApiV3CategoriesRouteImport.update({
  id: '/api/v3/categories',
  path: '/api/v3/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsSearchRoute = ApiJobsSearchRouteImport.update({
  id: '/api/jobs/search',
  path: '/api/jobs/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignOutRoute = ApiAuthSignOutRouteImport.update({
  id: '/api/auth/sign-out',
  path: '/api/auth/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGetSessionRoute = ApiAuthGetSessionRouteImport.update({
  id: '/api/auth/get-session',
  path: '/api/auth/get-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiUnicornRoute = ApiAiUnicornRouteImport.update({
  id: '/api/ai/unicorn',
  path: '/api/ai/unicorn',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiSearchRoute = ApiAiSearchRouteImport.update({
  id: '/api/ai/search',
  path: '/api/ai/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiScoreAllRoute = ApiAiScoreAllRouteImport.update({
  id: '/api/ai/score-all',
  path: '/api/ai/score-all',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiRecommendRoute = ApiAiRecommendRouteImport.update({
  id: '/api/ai/recommend',
  path: '/api/ai/recommend',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiMatchRoute = ApiAiMatchRouteImport.update({
  id: '/api/ai/match',
  path: '/api/ai/match',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiInsightsRoute = ApiAiInsightsRouteImport.update({
  id: '/api/ai/insights',
  path: '/api/ai/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiGenerateResumeRoute = ApiAiGenerateResumeRouteImport.update({
  id: '/api/ai/generate-resume',
  path: '/api/ai/generate-resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCleanupNonUsJobsRoute =
  ApiAdminCleanupNonUsJobsRouteImport.update({
    id: '/api/admin/cleanup-non-us-jobs',
    path: '/api/admin/cleanup-non-us-jobs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV3JobsPruneRoute = ApiV3JobsPruneRouteImport.update({
  id: '/prune',
  path: '/prune',
  getParentRoute: () => ApiV3JobsRoute,
} as any)
const ApiAuthSignUpEmailRoute = ApiAuthSignUpEmailRouteImport.update({
  id: '/api/auth/sign-up/email',
  path: '/api/auth/sign-up/email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignInEmailRoute = ApiAuthSignInEmailRouteImport.update({
  id: '/api/auth/sign-in/email',
  path: '/api/auth/sign-in/email',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-setup': typeof AdminSetupRoute
  '/dashboard': typeof DashboardRoute
  '/jobs': typeof JobsRoute
  '/linkedin-jobs': typeof LinkedinJobsRoute
  '/linkedin-search': typeof LinkedinSearchRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/sync': typeof SyncRoute
  '/api/test': typeof ApiTestRoute
  '/api/admin/cleanup-non-us-jobs': typeof ApiAdminCleanupNonUsJobsRoute
  '/api/ai/generate-resume': typeof ApiAiGenerateResumeRoute
  '/api/ai/insights': typeof ApiAiInsightsRoute
  '/api/ai/match': typeof ApiAiMatchRoute
  '/api/ai/recommend': typeof ApiAiRecommendRoute
  '/api/ai/score-all': typeof ApiAiScoreAllRoute
  '/api/ai/search': typeof ApiAiSearchRoute
  '/api/ai/unicorn': typeof ApiAiUnicornRoute
  '/api/auth/get-session': typeof ApiAuthGetSessionRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/api/jobs/search': typeof ApiJobsSearchRoute
  '/api/v3/categories': typeof ApiV3CategoriesRoute
  '/api/v3/job-content': typeof ApiV3JobContentRoute
  '/api/v3/jobs': typeof ApiV3JobsRouteWithChildren
  '/api/v3/logs': typeof ApiV3LogsRoute
  '/api/v3/stats': typeof ApiV3StatsRoute
  '/api/auth/sign-in/email': typeof ApiAuthSignInEmailRoute
  '/api/auth/sign-up/email': typeof ApiAuthSignUpEmailRoute
  '/api/v3/jobs/prune': typeof ApiV3JobsPruneRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-setup': typeof AdminSetupRoute
  '/dashboard': typeof DashboardRoute
  '/jobs': typeof JobsRoute
  '/linkedin-jobs': typeof LinkedinJobsRoute
  '/linkedin-search': typeof LinkedinSearchRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/sync': typeof SyncRoute
  '/api/test': typeof ApiTestRoute
  '/api/admin/cleanup-non-us-jobs': typeof ApiAdminCleanupNonUsJobsRoute
  '/api/ai/generate-resume': typeof ApiAiGenerateResumeRoute
  '/api/ai/insights': typeof ApiAiInsightsRoute
  '/api/ai/match': typeof ApiAiMatchRoute
  '/api/ai/recommend': typeof ApiAiRecommendRoute
  '/api/ai/score-all': typeof ApiAiScoreAllRoute
  '/api/ai/search': typeof ApiAiSearchRoute
  '/api/ai/unicorn': typeof ApiAiUnicornRoute
  '/api/auth/get-session': typeof ApiAuthGetSessionRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/api/jobs/search': typeof ApiJobsSearchRoute
  '/api/v3/categories': typeof ApiV3CategoriesRoute
  '/api/v3/job-content': typeof ApiV3JobContentRoute
  '/api/v3/jobs': typeof ApiV3JobsRouteWithChildren
  '/api/v3/logs': typeof ApiV3LogsRoute
  '/api/v3/stats': typeof ApiV3StatsRoute
  '/api/auth/sign-in/email': typeof ApiAuthSignInEmailRoute
  '/api/auth/sign-up/email': typeof ApiAuthSignUpEmailRoute
  '/api/v3/jobs/prune': typeof ApiV3JobsPruneRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-setup': typeof AdminSetupRoute
  '/dashboard': typeof DashboardRoute
  '/jobs': typeof JobsRoute
  '/linkedin-jobs': typeof LinkedinJobsRoute
  '/linkedin-search': typeof LinkedinSearchRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/sync': typeof SyncRoute
  '/api/test': typeof ApiTestRoute
  '/api/admin/cleanup-non-us-jobs': typeof ApiAdminCleanupNonUsJobsRoute
  '/api/ai/generate-resume': typeof ApiAiGenerateResumeRoute
  '/api/ai/insights': typeof ApiAiInsightsRoute
  '/api/ai/match': typeof ApiAiMatchRoute
  '/api/ai/recommend': typeof ApiAiRecommendRoute
  '/api/ai/score-all': typeof ApiAiScoreAllRoute
  '/api/ai/search': typeof ApiAiSearchRoute
  '/api/ai/unicorn': typeof ApiAiUnicornRoute
  '/api/auth/get-session': typeof ApiAuthGetSessionRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/api/jobs/search': typeof ApiJobsSearchRoute
  '/api/v3/categories': typeof ApiV3CategoriesRoute
  '/api/v3/job-content': typeof ApiV3JobContentRoute
  '/api/v3/jobs': typeof ApiV3JobsRouteWithChildren
  '/api/v3/logs': typeof ApiV3LogsRoute
  '/api/v3/stats': typeof ApiV3StatsRoute
  '/api/auth/sign-in/email': typeof ApiAuthSignInEmailRoute
  '/api/auth/sign-up/email': typeof ApiAuthSignUpEmailRoute
  '/api/v3/jobs/prune': typeof ApiV3JobsPruneRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-setup'
    | '/dashboard'
    | '/jobs'
    | '/linkedin-jobs'
    | '/linkedin-search'
    | '/login'
    | '/logs'
    | '/profile'
    | '/signup'
    | '/sync'
    | '/api/test'
    | '/api/admin/cleanup-non-us-jobs'
    | '/api/ai/generate-resume'
    | '/api/ai/insights'
    | '/api/ai/match'
    | '/api/ai/recommend'
    | '/api/ai/score-all'
    | '/api/ai/search'
    | '/api/ai/unicorn'
    | '/api/auth/get-session'
    | '/api/auth/sign-out'
    | '/api/jobs/search'
    | '/api/v3/categories'
    | '/api/v3/job-content'
    | '/api/v3/jobs'
    | '/api/v3/logs'
    | '/api/v3/stats'
    | '/api/auth/sign-in/email'
    | '/api/auth/sign-up/email'
    | '/api/v3/jobs/prune'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-setup'
    | '/dashboard'
    | '/jobs'
    | '/linkedin-jobs'
    | '/linkedin-search'
    | '/login'
    | '/logs'
    | '/profile'
    | '/signup'
    | '/sync'
    | '/api/test'
    | '/api/admin/cleanup-non-us-jobs'
    | '/api/ai/generate-resume'
    | '/api/ai/insights'
    | '/api/ai/match'
    | '/api/ai/recommend'
    | '/api/ai/score-all'
    | '/api/ai/search'
    | '/api/ai/unicorn'
    | '/api/auth/get-session'
    | '/api/auth/sign-out'
    | '/api/jobs/search'
    | '/api/v3/categories'
    | '/api/v3/job-content'
    | '/api/v3/jobs'
    | '/api/v3/logs'
    | '/api/v3/stats'
    | '/api/auth/sign-in/email'
    | '/api/auth/sign-up/email'
    | '/api/v3/jobs/prune'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-setup'
    | '/dashboard'
    | '/jobs'
    | '/linkedin-jobs'
    | '/linkedin-search'
    | '/login'
    | '/logs'
    | '/profile'
    | '/signup'
    | '/sync'
    | '/api/test'
    | '/api/admin/cleanup-non-us-jobs'
    | '/api/ai/generate-resume'
    | '/api/ai/insights'
    | '/api/ai/match'
    | '/api/ai/recommend'
    | '/api/ai/score-all'
    | '/api/ai/search'
    | '/api/ai/unicorn'
    | '/api/auth/get-session'
    | '/api/auth/sign-out'
    | '/api/jobs/search'
    | '/api/v3/categories'
    | '/api/v3/job-content'
    | '/api/v3/jobs'
    | '/api/v3/logs'
    | '/api/v3/stats'
    | '/api/auth/sign-in/email'
    | '/api/auth/sign-up/email'
    | '/api/v3/jobs/prune'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminSetupRoute: typeof AdminSetupRoute
  DashboardRoute: typeof DashboardRoute
  JobsRoute: typeof JobsRoute
  LinkedinJobsRoute: typeof LinkedinJobsRoute
  LinkedinSearchRoute: typeof LinkedinSearchRoute
  LoginRoute: typeof LoginRoute
  LogsRoute: typeof LogsRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  SyncRoute: typeof SyncRoute
  ApiTestRoute: typeof ApiTestRoute
  ApiAdminCleanupNonUsJobsRoute: typeof ApiAdminCleanupNonUsJobsRoute
  ApiAiGenerateResumeRoute: typeof ApiAiGenerateResumeRoute
  ApiAiInsightsRoute: typeof ApiAiInsightsRoute
  ApiAiMatchRoute: typeof ApiAiMatchRoute
  ApiAiRecommendRoute: typeof ApiAiRecommendRoute
  ApiAiScoreAllRoute: typeof ApiAiScoreAllRoute
  ApiAiSearchRoute: typeof ApiAiSearchRoute
  ApiAiUnicornRoute: typeof ApiAiUnicornRoute
  ApiAuthGetSessionRoute: typeof ApiAuthGetSessionRoute
  ApiAuthSignOutRoute: typeof ApiAuthSignOutRoute
  ApiJobsSearchRoute: typeof ApiJobsSearchRoute
  ApiV3CategoriesRoute: typeof ApiV3CategoriesRoute
  ApiV3JobContentRoute: typeof ApiV3JobContentRoute
  ApiV3JobsRoute: typeof ApiV3JobsRouteWithChildren
  ApiV3LogsRoute: typeof ApiV3LogsRoute
  ApiV3StatsRoute: typeof ApiV3StatsRoute
  ApiAuthSignInEmailRoute: typeof ApiAuthSignInEmailRoute
  ApiAuthSignUpEmailRoute: typeof ApiAuthSignUpEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sync': {
      id: '/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof SyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linkedin-search': {
      id: '/linkedin-search'
      path: '/linkedin-search'
      fullPath: '/linkedin-search'
      preLoaderRoute: typeof LinkedinSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linkedin-jobs': {
      id: '/linkedin-jobs'
      path: '/linkedin-jobs'
      fullPath: '/linkedin-jobs'
      preLoaderRoute: typeof LinkedinJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-setup': {
      id: '/admin-setup'
      path: '/admin-setup'
      fullPath: '/admin-setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test': {
      id: '/api/test'
      path: '/api/test'
      fullPath: '/api/test'
      preLoaderRoute: typeof ApiTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v3/stats': {
      id: '/api/v3/stats'
      path: '/api/v3/stats'
      fullPath: '/api/v3/stats'
      preLoaderRoute: typeof ApiV3StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v3/logs': {
      id: '/api/v3/logs'
      path: '/api/v3/logs'
      fullPath: '/api/v3/logs'
      preLoaderRoute: typeof ApiV3LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v3/jobs': {
      id: '/api/v3/jobs'
      path: '/api/v3/jobs'
      fullPath: '/api/v3/jobs'
      preLoaderRoute: typeof ApiV3JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v3/job-content': {
      id: '/api/v3/job-content'
      path: '/api/v3/job-content'
      fullPath: '/api/v3/job-content'
      preLoaderRoute: typeof ApiV3JobContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v3/categories': {
      id: '/api/v3/categories'
      path: '/api/v3/categories'
      fullPath: '/api/v3/categories'
      preLoaderRoute: typeof ApiV3CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/search': {
      id: '/api/jobs/search'
      path: '/api/jobs/search'
      fullPath: '/api/jobs/search'
      preLoaderRoute: typeof ApiJobsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-out': {
      id: '/api/auth/sign-out'
      path: '/api/auth/sign-out'
      fullPath: '/api/auth/sign-out'
      preLoaderRoute: typeof ApiAuthSignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/get-session': {
      id: '/api/auth/get-session'
      path: '/api/auth/get-session'
      fullPath: '/api/auth/get-session'
      preLoaderRoute: typeof ApiAuthGetSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/unicorn': {
      id: '/api/ai/unicorn'
      path: '/api/ai/unicorn'
      fullPath: '/api/ai/unicorn'
      preLoaderRoute: typeof ApiAiUnicornRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/search': {
      id: '/api/ai/search'
      path: '/api/ai/search'
      fullPath: '/api/ai/search'
      preLoaderRoute: typeof ApiAiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/score-all': {
      id: '/api/ai/score-all'
      path: '/api/ai/score-all'
      fullPath: '/api/ai/score-all'
      preLoaderRoute: typeof ApiAiScoreAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/recommend': {
      id: '/api/ai/recommend'
      path: '/api/ai/recommend'
      fullPath: '/api/ai/recommend'
      preLoaderRoute: typeof ApiAiRecommendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/match': {
      id: '/api/ai/match'
      path: '/api/ai/match'
      fullPath: '/api/ai/match'
      preLoaderRoute: typeof ApiAiMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/insights': {
      id: '/api/ai/insights'
      path: '/api/ai/insights'
      fullPath: '/api/ai/insights'
      preLoaderRoute: typeof ApiAiInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/generate-resume': {
      id: '/api/ai/generate-resume'
      path: '/api/ai/generate-resume'
      fullPath: '/api/ai/generate-resume'
      preLoaderRoute: typeof ApiAiGenerateResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/cleanup-non-us-jobs': {
      id: '/api/admin/cleanup-non-us-jobs'
      path: '/api/admin/cleanup-non-us-jobs'
      fullPath: '/api/admin/cleanup-non-us-jobs'
      preLoaderRoute: typeof ApiAdminCleanupNonUsJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v3/jobs/prune': {
      id: '/api/v3/jobs/prune'
      path: '/prune'
      fullPath: '/api/v3/jobs/prune'
      preLoaderRoute: typeof ApiV3JobsPruneRouteImport
      parentRoute: typeof ApiV3JobsRoute
    }
    '/api/auth/sign-up/email': {
      id: '/api/auth/sign-up/email'
      path: '/api/auth/sign-up/email'
      fullPath: '/api/auth/sign-up/email'
      preLoaderRoute: typeof ApiAuthSignUpEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-in/email': {
      id: '/api/auth/sign-in/email'
      path: '/api/auth/sign-in/email'
      fullPath: '/api/auth/sign-in/email'
      preLoaderRoute: typeof ApiAuthSignInEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiV3JobsRouteChildren {
  ApiV3JobsPruneRoute: typeof ApiV3JobsPruneRoute
}

const ApiV3JobsRouteChildren: ApiV3JobsRouteChildren = {
  ApiV3JobsPruneRoute: ApiV3JobsPruneRoute,
}

const ApiV3JobsRouteWithChildren = ApiV3JobsRoute._addFileChildren(
  ApiV3JobsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminSetupRoute: AdminSetupRoute,
  DashboardRoute: DashboardRoute,
  JobsRoute: JobsRoute,
  LinkedinJobsRoute: LinkedinJobsRoute,
  LinkedinSearchRoute: LinkedinSearchRoute,
  LoginRoute: LoginRoute,
  LogsRoute: LogsRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  SyncRoute: SyncRoute,
  ApiTestRoute: ApiTestRoute,
  ApiAdminCleanupNonUsJobsRoute: ApiAdminCleanupNonUsJobsRoute,
  ApiAiGenerateResumeRoute: ApiAiGenerateResumeRoute,
  ApiAiInsightsRoute: ApiAiInsightsRoute,
  ApiAiMatchRoute: ApiAiMatchRoute,
  ApiAiRecommendRoute: ApiAiRecommendRoute,
  ApiAiScoreAllRoute: ApiAiScoreAllRoute,
  ApiAiSearchRoute: ApiAiSearchRoute,
  ApiAiUnicornRoute: ApiAiUnicornRoute,
  ApiAuthGetSessionRoute: ApiAuthGetSessionRoute,
  ApiAuthSignOutRoute: ApiAuthSignOutRoute,
  ApiJobsSearchRoute: ApiJobsSearchRoute,
  ApiV3CategoriesRoute: ApiV3CategoriesRoute,
  ApiV3JobContentRoute: ApiV3JobContentRoute,
  ApiV3JobsRoute: ApiV3JobsRouteWithChildren,
  ApiV3LogsRoute: ApiV3LogsRoute,
  ApiV3StatsRoute: ApiV3StatsRoute,
  ApiAuthSignInEmailRoute: ApiAuthSignInEmailRoute,
  ApiAuthSignUpEmailRoute: ApiAuthSignUpEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
