/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SyncRouteImport } from './routes/sync'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MyJobsRouteImport } from './routes/my-jobs'
import { Route as MyAgentsRouteImport } from './routes/my-agents'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LinkedinSearchRouteImport } from './routes/linkedin-search'
import { Route as LinkedinJobsRouteImport } from './routes/linkedin-jobs'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as DiscoveryRouteImport } from './routes/discovery'
import { Route as CrawlerRouteImport } from './routes/crawler'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as AgentInsightsRouteImport } from './routes/agent-insights'
import { Route as AdminSetupRouteImport } from './routes/admin-setup'
import { Route as AdminSettingsRouteImport } from './routes/admin-settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTestRouteImport } from './routes/api/test'
import { Route as ApiSavedJobsRouteImport } from './routes/api/saved-jobs'
import { Route as ApiMetricsRouteImport } from './routes/api/metrics'
import { Route as ApiV3StatsRouteImport } from './routes/api/v3/stats'
import { Route as ApiV3LogsRouteImport } from './routes/api/v3/logs'
import { Route as ApiV3JobsRouteImport } from './routes/api/v3/jobs'
import { Route as ApiV3JobContentRouteImport } from './routes/api/v3/job-content'
import { Route as ApiV3CategoriesRouteImport } from './routes/api/v3/categories'
import { Route as ApiJobsSearchRouteImport } from './routes/api/jobs/search'
import { Route as ApiJobsCrawlerSearchRouteImport } from './routes/api/jobs/crawler-search'
import { Route as ApiDiscoveryValidateBoardRouteImport } from './routes/api/discovery/validate-board'
import { Route as ApiDiscoveryStatsRouteImport } from './routes/api/discovery/stats'
import { Route as ApiDiscoveryRunPhaseRouteImport } from './routes/api/discovery/run-phase'
import { Route as ApiDiscoveryDeleteBoardRouteImport } from './routes/api/discovery/delete-board'
import { Route as ApiDiscoveryCronRouteImport } from './routes/api/discovery/cron'
import { Route as ApiCrawlToggleBoardRouteImport } from './routes/api/crawl/toggle-board'
import { Route as ApiCrawlStatsRouteImport } from './routes/api/crawl/stats'
import { Route as ApiCrawlSaveBoardRouteImport } from './routes/api/crawl/save-board'
import { Route as ApiCrawlCronRouteImport } from './routes/api/crawl/cron'
import { Route as ApiCrawlAtsRouteImport } from './routes/api/crawl/$ats'
import { Route as ApiAuthSignOutRouteImport } from './routes/api/auth/sign-out'
import { Route as ApiAuthGetSessionRouteImport } from './routes/api/auth/get-session'
import { Route as ApiAiUnicornRouteImport } from './routes/api/ai/unicorn'
import { Route as ApiAiSearchRouteImport } from './routes/api/ai/search'
import { Route as ApiAiScoreAllRouteImport } from './routes/api/ai/score-all'
import { Route as ApiAiRecommendRouteImport } from './routes/api/ai/recommend'
import { Route as ApiAiMatchRouteImport } from './routes/api/ai/match'
import { Route as ApiAiInsightsRouteImport } from './routes/api/ai/insights'
import { Route as ApiAiGenerateResumeRouteImport } from './routes/api/ai/generate-resume'
import { Route as ApiAdminSeedVectorsRouteImport } from './routes/api/admin/seed-vectors'
import { Route as ApiAdminCleanupNonUsJobsRouteImport } from './routes/api/admin/cleanup-non-us-jobs'
import { Route as ApiV3JobsPruneRouteImport } from './routes/api/v3/jobs/prune'
import { Route as ApiAuthSignUpEmailRouteImport } from './routes/api/auth/sign-up/email'
import { Route as ApiAuthSignInEmailRouteImport } from './routes/api/auth/sign-in/email'

const SyncRoute = SyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MyJobsRoute = MyJobsRouteImport.update({
  id: '/my-jobs',
  path: '/my-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const MyAgentsRoute = MyAgentsRouteImport.update({
  id: '/my-agents',
  path: '/my-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkedinSearchRoute = LinkedinSearchRouteImport.update({
  id: '/linkedin-search',
  path: '/linkedin-search',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkedinJobsRoute = LinkedinJobsRouteImport.update({
  id: '/linkedin-jobs',
  path: '/linkedin-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveryRoute = DiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const CrawlerRoute = CrawlerRouteImport.update({
  id: '/crawler',
  path: '/crawler',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentInsightsRoute = AgentInsightsRouteImport.update({
  id: '/agent-insights',
  path: '/agent-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/admin-setup',
  path: '/admin-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin-settings',
  path: '/admin-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestRoute = ApiTestRouteImport.update({
  id: '/api/test',
  path: '/api/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSavedJobsRoute = ApiSavedJobsRouteImport.update({
  id: '/api/saved-jobs',
  path: '/api/saved-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetricsRoute = ApiMetricsRouteImport.update({
  id: '/api/metrics',
  path: '/api/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV3StatsRoute = ApiV3StatsRouteImport.update({
  id: '/api/v3/stats',
  path: '/api/v3/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV3LogsRoute = ApiV3LogsRouteImport.update({
  id: '/api/v3/logs',
  path: '/api/v3/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV3JobsRoute = ApiV3JobsRouteImport.update({
  id: '/api/v3/jobs',
  path: '/api/v3/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV3JobContentRoute = ApiV3JobContentRouteImport.update({
  id: '/api/v3/job-content',
  path: '/api/v3/job-content',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV3CategoriesRoute = ApiV3CategoriesRouteImport.update({
  id: '/api/v3/categories',
  path: '/api/v3/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsSearchRoute = ApiJobsSearchRouteImport.update({
  id: '/api/jobs/search',
  path: '/api/jobs/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsCrawlerSearchRoute = ApiJobsCrawlerSearchRouteImport.update({
  id: '/api/jobs/crawler-search',
  path: '/api/jobs/crawler-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiscoveryValidateBoardRoute =
  ApiDiscoveryValidateBoardRouteImport.update({
    id: '/api/discovery/validate-board',
    path: '/api/discovery/validate-board',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDiscoveryStatsRoute = ApiDiscoveryStatsRouteImport.update({
  id: '/api/discovery/stats',
  path: '/api/discovery/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiscoveryRunPhaseRoute = ApiDiscoveryRunPhaseRouteImport.update({
  id: '/api/discovery/run-phase',
  path: '/api/discovery/run-phase',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiscoveryDeleteBoardRoute = ApiDiscoveryDeleteBoardRouteImport.update({
  id: '/api/discovery/delete-board',
  path: '/api/discovery/delete-board',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiscoveryCronRoute = ApiDiscoveryCronRouteImport.update({
  id: '/api/discovery/cron',
  path: '/api/discovery/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrawlToggleBoardRoute = ApiCrawlToggleBoardRouteImport.update({
  id: '/api/crawl/toggle-board',
  path: '/api/crawl/toggle-board',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrawlStatsRoute = ApiCrawlStatsRouteImport.update({
  id: '/api/crawl/stats',
  path: '/api/crawl/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrawlSaveBoardRoute = ApiCrawlSaveBoardRouteImport.update({
  id: '/api/crawl/save-board',
  path: '/api/crawl/save-board',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrawlCronRoute = ApiCrawlCronRouteImport.update({
  id: '/api/crawl/cron',
  path: '/api/crawl/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrawlAtsRoute = ApiCrawlAtsRouteImport.update({
  id: '/api/crawl/$ats',
  path: '/api/crawl/$ats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignOutRoute = ApiAuthSignOutRouteImport.update({
  id: '/api/auth/sign-out',
  path: '/api/auth/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGetSessionRoute = ApiAuthGetSessionRouteImport.update({
  id: '/api/auth/get-session',
  path: '/api/auth/get-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiUnicornRoute = ApiAiUnicornRouteImport.update({
  id: '/api/ai/unicorn',
  path: '/api/ai/unicorn',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiSearchRoute = ApiAiSearchRouteImport.update({
  id: '/api/ai/search',
  path: '/api/ai/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiScoreAllRoute = ApiAiScoreAllRouteImport.update({
  id: '/api/ai/score-all',
  path: '/api/ai/score-all',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiRecommendRoute = ApiAiRecommendRouteImport.update({
  id: '/api/ai/recommend',
  path: '/api/ai/recommend',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiMatchRoute = ApiAiMatchRouteImport.update({
  id: '/api/ai/match',
  path: '/api/ai/match',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiInsightsRoute = ApiAiInsightsRouteImport.update({
  id: '/api/ai/insights',
  path: '/api/ai/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiGenerateResumeRoute = ApiAiGenerateResumeRouteImport.update({
  id: '/api/ai/generate-resume',
  path: '/api/ai/generate-resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSeedVectorsRoute = ApiAdminSeedVectorsRouteImport.update({
  id: '/api/admin/seed-vectors',
  path: '/api/admin/seed-vectors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCleanupNonUsJobsRoute =
  ApiAdminCleanupNonUsJobsRouteImport.update({
    id: '/api/admin/cleanup-non-us-jobs',
    path: '/api/admin/cleanup-non-us-jobs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV3JobsPruneRoute = ApiV3JobsPruneRouteImport.update({
  id: '/prune',
  path: '/prune',
  getParentRoute: () => ApiV3JobsRoute,
} as any)
const ApiAuthSignUpEmailRoute = ApiAuthSignUpEmailRouteImport.update({
  id: '/api/auth/sign-up/email',
  path: '/api/auth/sign-up/email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignInEmailRoute = ApiAuthSignInEmailRouteImport.update({
  id: '/api/auth/sign-in/email',
  path: '/api/auth/sign-in/email',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-settings': typeof AdminSettingsRoute
  '/admin-setup': typeof AdminSetupRoute
  '/agent-insights': typeof AgentInsightsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/crawler': typeof CrawlerRoute
  '/discovery': typeof DiscoveryRoute
  '/insights': typeof InsightsRoute
  '/jobs': typeof JobsRoute
  '/linkedin-jobs': typeof LinkedinJobsRoute
  '/linkedin-search': typeof LinkedinSearchRoute
  '/login': typeof LoginRoute
  '/my-agents': typeof MyAgentsRoute
  '/my-jobs': typeof MyJobsRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/sync': typeof SyncRoute
  '/api/metrics': typeof ApiMetricsRoute
  '/api/saved-jobs': typeof ApiSavedJobsRoute
  '/api/test': typeof ApiTestRoute
  '/api/admin/cleanup-non-us-jobs': typeof ApiAdminCleanupNonUsJobsRoute
  '/api/admin/seed-vectors': typeof ApiAdminSeedVectorsRoute
  '/api/ai/generate-resume': typeof ApiAiGenerateResumeRoute
  '/api/ai/insights': typeof ApiAiInsightsRoute
  '/api/ai/match': typeof ApiAiMatchRoute
  '/api/ai/recommend': typeof ApiAiRecommendRoute
  '/api/ai/score-all': typeof ApiAiScoreAllRoute
  '/api/ai/search': typeof ApiAiSearchRoute
  '/api/ai/unicorn': typeof ApiAiUnicornRoute
  '/api/auth/get-session': typeof ApiAuthGetSessionRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/api/crawl/$ats': typeof ApiCrawlAtsRoute
  '/api/crawl/cron': typeof ApiCrawlCronRoute
  '/api/crawl/save-board': typeof ApiCrawlSaveBoardRoute
  '/api/crawl/stats': typeof ApiCrawlStatsRoute
  '/api/crawl/toggle-board': typeof ApiCrawlToggleBoardRoute
  '/api/discovery/cron': typeof ApiDiscoveryCronRoute
  '/api/discovery/delete-board': typeof ApiDiscoveryDeleteBoardRoute
  '/api/discovery/run-phase': typeof ApiDiscoveryRunPhaseRoute
  '/api/discovery/stats': typeof ApiDiscoveryStatsRoute
  '/api/discovery/validate-board': typeof ApiDiscoveryValidateBoardRoute
  '/api/jobs/crawler-search': typeof ApiJobsCrawlerSearchRoute
  '/api/jobs/search': typeof ApiJobsSearchRoute
  '/api/v3/categories': typeof ApiV3CategoriesRoute
  '/api/v3/job-content': typeof ApiV3JobContentRoute
  '/api/v3/jobs': typeof ApiV3JobsRouteWithChildren
  '/api/v3/logs': typeof ApiV3LogsRoute
  '/api/v3/stats': typeof ApiV3StatsRoute
  '/api/auth/sign-in/email': typeof ApiAuthSignInEmailRoute
  '/api/auth/sign-up/email': typeof ApiAuthSignUpEmailRoute
  '/api/v3/jobs/prune': typeof ApiV3JobsPruneRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-settings': typeof AdminSettingsRoute
  '/admin-setup': typeof AdminSetupRoute
  '/agent-insights': typeof AgentInsightsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/crawler': typeof CrawlerRoute
  '/discovery': typeof DiscoveryRoute
  '/insights': typeof InsightsRoute
  '/jobs': typeof JobsRoute
  '/linkedin-jobs': typeof LinkedinJobsRoute
  '/linkedin-search': typeof LinkedinSearchRoute
  '/login': typeof LoginRoute
  '/my-agents': typeof MyAgentsRoute
  '/my-jobs': typeof MyJobsRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/sync': typeof SyncRoute
  '/api/metrics': typeof ApiMetricsRoute
  '/api/saved-jobs': typeof ApiSavedJobsRoute
  '/api/test': typeof ApiTestRoute
  '/api/admin/cleanup-non-us-jobs': typeof ApiAdminCleanupNonUsJobsRoute
  '/api/admin/seed-vectors': typeof ApiAdminSeedVectorsRoute
  '/api/ai/generate-resume': typeof ApiAiGenerateResumeRoute
  '/api/ai/insights': typeof ApiAiInsightsRoute
  '/api/ai/match': typeof ApiAiMatchRoute
  '/api/ai/recommend': typeof ApiAiRecommendRoute
  '/api/ai/score-all': typeof ApiAiScoreAllRoute
  '/api/ai/search': typeof ApiAiSearchRoute
  '/api/ai/unicorn': typeof ApiAiUnicornRoute
  '/api/auth/get-session': typeof ApiAuthGetSessionRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/api/crawl/$ats': typeof ApiCrawlAtsRoute
  '/api/crawl/cron': typeof ApiCrawlCronRoute
  '/api/crawl/save-board': typeof ApiCrawlSaveBoardRoute
  '/api/crawl/stats': typeof ApiCrawlStatsRoute
  '/api/crawl/toggle-board': typeof ApiCrawlToggleBoardRoute
  '/api/discovery/cron': typeof ApiDiscoveryCronRoute
  '/api/discovery/delete-board': typeof ApiDiscoveryDeleteBoardRoute
  '/api/discovery/run-phase': typeof ApiDiscoveryRunPhaseRoute
  '/api/discovery/stats': typeof ApiDiscoveryStatsRoute
  '/api/discovery/validate-board': typeof ApiDiscoveryValidateBoardRoute
  '/api/jobs/crawler-search': typeof ApiJobsCrawlerSearchRoute
  '/api/jobs/search': typeof ApiJobsSearchRoute
  '/api/v3/categories': typeof ApiV3CategoriesRoute
  '/api/v3/job-content': typeof ApiV3JobContentRoute
  '/api/v3/jobs': typeof ApiV3JobsRouteWithChildren
  '/api/v3/logs': typeof ApiV3LogsRoute
  '/api/v3/stats': typeof ApiV3StatsRoute
  '/api/auth/sign-in/email': typeof ApiAuthSignInEmailRoute
  '/api/auth/sign-up/email': typeof ApiAuthSignUpEmailRoute
  '/api/v3/jobs/prune': typeof ApiV3JobsPruneRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-settings': typeof AdminSettingsRoute
  '/admin-setup': typeof AdminSetupRoute
  '/agent-insights': typeof AgentInsightsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/crawler': typeof CrawlerRoute
  '/discovery': typeof DiscoveryRoute
  '/insights': typeof InsightsRoute
  '/jobs': typeof JobsRoute
  '/linkedin-jobs': typeof LinkedinJobsRoute
  '/linkedin-search': typeof LinkedinSearchRoute
  '/login': typeof LoginRoute
  '/my-agents': typeof MyAgentsRoute
  '/my-jobs': typeof MyJobsRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/sync': typeof SyncRoute
  '/api/metrics': typeof ApiMetricsRoute
  '/api/saved-jobs': typeof ApiSavedJobsRoute
  '/api/test': typeof ApiTestRoute
  '/api/admin/cleanup-non-us-jobs': typeof ApiAdminCleanupNonUsJobsRoute
  '/api/admin/seed-vectors': typeof ApiAdminSeedVectorsRoute
  '/api/ai/generate-resume': typeof ApiAiGenerateResumeRoute
  '/api/ai/insights': typeof ApiAiInsightsRoute
  '/api/ai/match': typeof ApiAiMatchRoute
  '/api/ai/recommend': typeof ApiAiRecommendRoute
  '/api/ai/score-all': typeof ApiAiScoreAllRoute
  '/api/ai/search': typeof ApiAiSearchRoute
  '/api/ai/unicorn': typeof ApiAiUnicornRoute
  '/api/auth/get-session': typeof ApiAuthGetSessionRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/api/crawl/$ats': typeof ApiCrawlAtsRoute
  '/api/crawl/cron': typeof ApiCrawlCronRoute
  '/api/crawl/save-board': typeof ApiCrawlSaveBoardRoute
  '/api/crawl/stats': typeof ApiCrawlStatsRoute
  '/api/crawl/toggle-board': typeof ApiCrawlToggleBoardRoute
  '/api/discovery/cron': typeof ApiDiscoveryCronRoute
  '/api/discovery/delete-board': typeof ApiDiscoveryDeleteBoardRoute
  '/api/discovery/run-phase': typeof ApiDiscoveryRunPhaseRoute
  '/api/discovery/stats': typeof ApiDiscoveryStatsRoute
  '/api/discovery/validate-board': typeof ApiDiscoveryValidateBoardRoute
  '/api/jobs/crawler-search': typeof ApiJobsCrawlerSearchRoute
  '/api/jobs/search': typeof ApiJobsSearchRoute
  '/api/v3/categories': typeof ApiV3CategoriesRoute
  '/api/v3/job-content': typeof ApiV3JobContentRoute
  '/api/v3/jobs': typeof ApiV3JobsRouteWithChildren
  '/api/v3/logs': typeof ApiV3LogsRoute
  '/api/v3/stats': typeof ApiV3StatsRoute
  '/api/auth/sign-in/email': typeof ApiAuthSignInEmailRoute
  '/api/auth/sign-up/email': typeof ApiAuthSignUpEmailRoute
  '/api/v3/jobs/prune': typeof ApiV3JobsPruneRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-settings'
    | '/admin-setup'
    | '/agent-insights'
    | '/audit-logs'
    | '/crawler'
    | '/discovery'
    | '/insights'
    | '/jobs'
    | '/linkedin-jobs'
    | '/linkedin-search'
    | '/login'
    | '/my-agents'
    | '/my-jobs'
    | '/profile'
    | '/signup'
    | '/sync'
    | '/api/metrics'
    | '/api/saved-jobs'
    | '/api/test'
    | '/api/admin/cleanup-non-us-jobs'
    | '/api/admin/seed-vectors'
    | '/api/ai/generate-resume'
    | '/api/ai/insights'
    | '/api/ai/match'
    | '/api/ai/recommend'
    | '/api/ai/score-all'
    | '/api/ai/search'
    | '/api/ai/unicorn'
    | '/api/auth/get-session'
    | '/api/auth/sign-out'
    | '/api/crawl/$ats'
    | '/api/crawl/cron'
    | '/api/crawl/save-board'
    | '/api/crawl/stats'
    | '/api/crawl/toggle-board'
    | '/api/discovery/cron'
    | '/api/discovery/delete-board'
    | '/api/discovery/run-phase'
    | '/api/discovery/stats'
    | '/api/discovery/validate-board'
    | '/api/jobs/crawler-search'
    | '/api/jobs/search'
    | '/api/v3/categories'
    | '/api/v3/job-content'
    | '/api/v3/jobs'
    | '/api/v3/logs'
    | '/api/v3/stats'
    | '/api/auth/sign-in/email'
    | '/api/auth/sign-up/email'
    | '/api/v3/jobs/prune'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-settings'
    | '/admin-setup'
    | '/agent-insights'
    | '/audit-logs'
    | '/crawler'
    | '/discovery'
    | '/insights'
    | '/jobs'
    | '/linkedin-jobs'
    | '/linkedin-search'
    | '/login'
    | '/my-agents'
    | '/my-jobs'
    | '/profile'
    | '/signup'
    | '/sync'
    | '/api/metrics'
    | '/api/saved-jobs'
    | '/api/test'
    | '/api/admin/cleanup-non-us-jobs'
    | '/api/admin/seed-vectors'
    | '/api/ai/generate-resume'
    | '/api/ai/insights'
    | '/api/ai/match'
    | '/api/ai/recommend'
    | '/api/ai/score-all'
    | '/api/ai/search'
    | '/api/ai/unicorn'
    | '/api/auth/get-session'
    | '/api/auth/sign-out'
    | '/api/crawl/$ats'
    | '/api/crawl/cron'
    | '/api/crawl/save-board'
    | '/api/crawl/stats'
    | '/api/crawl/toggle-board'
    | '/api/discovery/cron'
    | '/api/discovery/delete-board'
    | '/api/discovery/run-phase'
    | '/api/discovery/stats'
    | '/api/discovery/validate-board'
    | '/api/jobs/crawler-search'
    | '/api/jobs/search'
    | '/api/v3/categories'
    | '/api/v3/job-content'
    | '/api/v3/jobs'
    | '/api/v3/logs'
    | '/api/v3/stats'
    | '/api/auth/sign-in/email'
    | '/api/auth/sign-up/email'
    | '/api/v3/jobs/prune'
  id:
    | '__root__'
    | '/'
    | '/admin-settings'
    | '/admin-setup'
    | '/agent-insights'
    | '/audit-logs'
    | '/crawler'
    | '/discovery'
    | '/insights'
    | '/jobs'
    | '/linkedin-jobs'
    | '/linkedin-search'
    | '/login'
    | '/my-agents'
    | '/my-jobs'
    | '/profile'
    | '/signup'
    | '/sync'
    | '/api/metrics'
    | '/api/saved-jobs'
    | '/api/test'
    | '/api/admin/cleanup-non-us-jobs'
    | '/api/admin/seed-vectors'
    | '/api/ai/generate-resume'
    | '/api/ai/insights'
    | '/api/ai/match'
    | '/api/ai/recommend'
    | '/api/ai/score-all'
    | '/api/ai/search'
    | '/api/ai/unicorn'
    | '/api/auth/get-session'
    | '/api/auth/sign-out'
    | '/api/crawl/$ats'
    | '/api/crawl/cron'
    | '/api/crawl/save-board'
    | '/api/crawl/stats'
    | '/api/crawl/toggle-board'
    | '/api/discovery/cron'
    | '/api/discovery/delete-board'
    | '/api/discovery/run-phase'
    | '/api/discovery/stats'
    | '/api/discovery/validate-board'
    | '/api/jobs/crawler-search'
    | '/api/jobs/search'
    | '/api/v3/categories'
    | '/api/v3/job-content'
    | '/api/v3/jobs'
    | '/api/v3/logs'
    | '/api/v3/stats'
    | '/api/auth/sign-in/email'
    | '/api/auth/sign-up/email'
    | '/api/v3/jobs/prune'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSetupRoute: typeof AdminSetupRoute
  AgentInsightsRoute: typeof AgentInsightsRoute
  AuditLogsRoute: typeof AuditLogsRoute
  CrawlerRoute: typeof CrawlerRoute
  DiscoveryRoute: typeof DiscoveryRoute
  InsightsRoute: typeof InsightsRoute
  JobsRoute: typeof JobsRoute
  LinkedinJobsRoute: typeof LinkedinJobsRoute
  LinkedinSearchRoute: typeof LinkedinSearchRoute
  LoginRoute: typeof LoginRoute
  MyAgentsRoute: typeof MyAgentsRoute
  MyJobsRoute: typeof MyJobsRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  SyncRoute: typeof SyncRoute
  ApiMetricsRoute: typeof ApiMetricsRoute
  ApiSavedJobsRoute: typeof ApiSavedJobsRoute
  ApiTestRoute: typeof ApiTestRoute
  ApiAdminCleanupNonUsJobsRoute: typeof ApiAdminCleanupNonUsJobsRoute
  ApiAdminSeedVectorsRoute: typeof ApiAdminSeedVectorsRoute
  ApiAiGenerateResumeRoute: typeof ApiAiGenerateResumeRoute
  ApiAiInsightsRoute: typeof ApiAiInsightsRoute
  ApiAiMatchRoute: typeof ApiAiMatchRoute
  ApiAiRecommendRoute: typeof ApiAiRecommendRoute
  ApiAiScoreAllRoute: typeof ApiAiScoreAllRoute
  ApiAiSearchRoute: typeof ApiAiSearchRoute
  ApiAiUnicornRoute: typeof ApiAiUnicornRoute
  ApiAuthGetSessionRoute: typeof ApiAuthGetSessionRoute
  ApiAuthSignOutRoute: typeof ApiAuthSignOutRoute
  ApiCrawlAtsRoute: typeof ApiCrawlAtsRoute
  ApiCrawlCronRoute: typeof ApiCrawlCronRoute
  ApiCrawlSaveBoardRoute: typeof ApiCrawlSaveBoardRoute
  ApiCrawlStatsRoute: typeof ApiCrawlStatsRoute
  ApiCrawlToggleBoardRoute: typeof ApiCrawlToggleBoardRoute
  ApiDiscoveryCronRoute: typeof ApiDiscoveryCronRoute
  ApiDiscoveryDeleteBoardRoute: typeof ApiDiscoveryDeleteBoardRoute
  ApiDiscoveryRunPhaseRoute: typeof ApiDiscoveryRunPhaseRoute
  ApiDiscoveryStatsRoute: typeof ApiDiscoveryStatsRoute
  ApiDiscoveryValidateBoardRoute: typeof ApiDiscoveryValidateBoardRoute
  ApiJobsCrawlerSearchRoute: typeof ApiJobsCrawlerSearchRoute
  ApiJobsSearchRoute: typeof ApiJobsSearchRoute
  ApiV3CategoriesRoute: typeof ApiV3CategoriesRoute
  ApiV3JobContentRoute: typeof ApiV3JobContentRoute
  ApiV3JobsRoute: typeof ApiV3JobsRouteWithChildren
  ApiV3LogsRoute: typeof ApiV3LogsRoute
  ApiV3StatsRoute: typeof ApiV3StatsRoute
  ApiAuthSignInEmailRoute: typeof ApiAuthSignInEmailRoute
  ApiAuthSignUpEmailRoute: typeof ApiAuthSignUpEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sync': {
      id: '/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof SyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-jobs': {
      id: '/my-jobs'
      path: '/my-jobs'
      fullPath: '/my-jobs'
      preLoaderRoute: typeof MyJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-agents': {
      id: '/my-agents'
      path: '/my-agents'
      fullPath: '/my-agents'
      preLoaderRoute: typeof MyAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linkedin-search': {
      id: '/linkedin-search'
      path: '/linkedin-search'
      fullPath: '/linkedin-search'
      preLoaderRoute: typeof LinkedinSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linkedin-jobs': {
      id: '/linkedin-jobs'
      path: '/linkedin-jobs'
      fullPath: '/linkedin-jobs'
      preLoaderRoute: typeof LinkedinJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovery': {
      id: '/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof DiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crawler': {
      id: '/crawler'
      path: '/crawler'
      fullPath: '/crawler'
      preLoaderRoute: typeof CrawlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-insights': {
      id: '/agent-insights'
      path: '/agent-insights'
      fullPath: '/agent-insights'
      preLoaderRoute: typeof AgentInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-setup': {
      id: '/admin-setup'
      path: '/admin-setup'
      fullPath: '/admin-setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-settings': {
      id: '/admin-settings'
      path: '/admin-settings'
      fullPath: '/admin-settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test': {
      id: '/api/test'
      path: '/api/test'
      fullPath: '/api/test'
      preLoaderRoute: typeof ApiTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/saved-jobs': {
      id: '/api/saved-jobs'
      path: '/api/saved-jobs'
      fullPath: '/api/saved-jobs'
      preLoaderRoute: typeof ApiSavedJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/metrics': {
      id: '/api/metrics'
      path: '/api/metrics'
      fullPath: '/api/metrics'
      preLoaderRoute: typeof ApiMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v3/stats': {
      id: '/api/v3/stats'
      path: '/api/v3/stats'
      fullPath: '/api/v3/stats'
      preLoaderRoute: typeof ApiV3StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v3/logs': {
      id: '/api/v3/logs'
      path: '/api/v3/logs'
      fullPath: '/api/v3/logs'
      preLoaderRoute: typeof ApiV3LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v3/jobs': {
      id: '/api/v3/jobs'
      path: '/api/v3/jobs'
      fullPath: '/api/v3/jobs'
      preLoaderRoute: typeof ApiV3JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v3/job-content': {
      id: '/api/v3/job-content'
      path: '/api/v3/job-content'
      fullPath: '/api/v3/job-content'
      preLoaderRoute: typeof ApiV3JobContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v3/categories': {
      id: '/api/v3/categories'
      path: '/api/v3/categories'
      fullPath: '/api/v3/categories'
      preLoaderRoute: typeof ApiV3CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/search': {
      id: '/api/jobs/search'
      path: '/api/jobs/search'
      fullPath: '/api/jobs/search'
      preLoaderRoute: typeof ApiJobsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/crawler-search': {
      id: '/api/jobs/crawler-search'
      path: '/api/jobs/crawler-search'
      fullPath: '/api/jobs/crawler-search'
      preLoaderRoute: typeof ApiJobsCrawlerSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/discovery/validate-board': {
      id: '/api/discovery/validate-board'
      path: '/api/discovery/validate-board'
      fullPath: '/api/discovery/validate-board'
      preLoaderRoute: typeof ApiDiscoveryValidateBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/discovery/stats': {
      id: '/api/discovery/stats'
      path: '/api/discovery/stats'
      fullPath: '/api/discovery/stats'
      preLoaderRoute: typeof ApiDiscoveryStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/discovery/run-phase': {
      id: '/api/discovery/run-phase'
      path: '/api/discovery/run-phase'
      fullPath: '/api/discovery/run-phase'
      preLoaderRoute: typeof ApiDiscoveryRunPhaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/discovery/delete-board': {
      id: '/api/discovery/delete-board'
      path: '/api/discovery/delete-board'
      fullPath: '/api/discovery/delete-board'
      preLoaderRoute: typeof ApiDiscoveryDeleteBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/discovery/cron': {
      id: '/api/discovery/cron'
      path: '/api/discovery/cron'
      fullPath: '/api/discovery/cron'
      preLoaderRoute: typeof ApiDiscoveryCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crawl/toggle-board': {
      id: '/api/crawl/toggle-board'
      path: '/api/crawl/toggle-board'
      fullPath: '/api/crawl/toggle-board'
      preLoaderRoute: typeof ApiCrawlToggleBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crawl/stats': {
      id: '/api/crawl/stats'
      path: '/api/crawl/stats'
      fullPath: '/api/crawl/stats'
      preLoaderRoute: typeof ApiCrawlStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crawl/save-board': {
      id: '/api/crawl/save-board'
      path: '/api/crawl/save-board'
      fullPath: '/api/crawl/save-board'
      preLoaderRoute: typeof ApiCrawlSaveBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crawl/cron': {
      id: '/api/crawl/cron'
      path: '/api/crawl/cron'
      fullPath: '/api/crawl/cron'
      preLoaderRoute: typeof ApiCrawlCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crawl/$ats': {
      id: '/api/crawl/$ats'
      path: '/api/crawl/$ats'
      fullPath: '/api/crawl/$ats'
      preLoaderRoute: typeof ApiCrawlAtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-out': {
      id: '/api/auth/sign-out'
      path: '/api/auth/sign-out'
      fullPath: '/api/auth/sign-out'
      preLoaderRoute: typeof ApiAuthSignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/get-session': {
      id: '/api/auth/get-session'
      path: '/api/auth/get-session'
      fullPath: '/api/auth/get-session'
      preLoaderRoute: typeof ApiAuthGetSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/unicorn': {
      id: '/api/ai/unicorn'
      path: '/api/ai/unicorn'
      fullPath: '/api/ai/unicorn'
      preLoaderRoute: typeof ApiAiUnicornRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/search': {
      id: '/api/ai/search'
      path: '/api/ai/search'
      fullPath: '/api/ai/search'
      preLoaderRoute: typeof ApiAiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/score-all': {
      id: '/api/ai/score-all'
      path: '/api/ai/score-all'
      fullPath: '/api/ai/score-all'
      preLoaderRoute: typeof ApiAiScoreAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/recommend': {
      id: '/api/ai/recommend'
      path: '/api/ai/recommend'
      fullPath: '/api/ai/recommend'
      preLoaderRoute: typeof ApiAiRecommendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/match': {
      id: '/api/ai/match'
      path: '/api/ai/match'
      fullPath: '/api/ai/match'
      preLoaderRoute: typeof ApiAiMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/insights': {
      id: '/api/ai/insights'
      path: '/api/ai/insights'
      fullPath: '/api/ai/insights'
      preLoaderRoute: typeof ApiAiInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/generate-resume': {
      id: '/api/ai/generate-resume'
      path: '/api/ai/generate-resume'
      fullPath: '/api/ai/generate-resume'
      preLoaderRoute: typeof ApiAiGenerateResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/seed-vectors': {
      id: '/api/admin/seed-vectors'
      path: '/api/admin/seed-vectors'
      fullPath: '/api/admin/seed-vectors'
      preLoaderRoute: typeof ApiAdminSeedVectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/cleanup-non-us-jobs': {
      id: '/api/admin/cleanup-non-us-jobs'
      path: '/api/admin/cleanup-non-us-jobs'
      fullPath: '/api/admin/cleanup-non-us-jobs'
      preLoaderRoute: typeof ApiAdminCleanupNonUsJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v3/jobs/prune': {
      id: '/api/v3/jobs/prune'
      path: '/prune'
      fullPath: '/api/v3/jobs/prune'
      preLoaderRoute: typeof ApiV3JobsPruneRouteImport
      parentRoute: typeof ApiV3JobsRoute
    }
    '/api/auth/sign-up/email': {
      id: '/api/auth/sign-up/email'
      path: '/api/auth/sign-up/email'
      fullPath: '/api/auth/sign-up/email'
      preLoaderRoute: typeof ApiAuthSignUpEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-in/email': {
      id: '/api/auth/sign-in/email'
      path: '/api/auth/sign-in/email'
      fullPath: '/api/auth/sign-in/email'
      preLoaderRoute: typeof ApiAuthSignInEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiV3JobsRouteChildren {
  ApiV3JobsPruneRoute: typeof ApiV3JobsPruneRoute
}

const ApiV3JobsRouteChildren: ApiV3JobsRouteChildren = {
  ApiV3JobsPruneRoute: ApiV3JobsPruneRoute,
}

const ApiV3JobsRouteWithChildren = ApiV3JobsRoute._addFileChildren(
  ApiV3JobsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSetupRoute: AdminSetupRoute,
  AgentInsightsRoute: AgentInsightsRoute,
  AuditLogsRoute: AuditLogsRoute,
  CrawlerRoute: CrawlerRoute,
  DiscoveryRoute: DiscoveryRoute,
  InsightsRoute: InsightsRoute,
  JobsRoute: JobsRoute,
  LinkedinJobsRoute: LinkedinJobsRoute,
  LinkedinSearchRoute: LinkedinSearchRoute,
  LoginRoute: LoginRoute,
  MyAgentsRoute: MyAgentsRoute,
  MyJobsRoute: MyJobsRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  SyncRoute: SyncRoute,
  ApiMetricsRoute: ApiMetricsRoute,
  ApiSavedJobsRoute: ApiSavedJobsRoute,
  ApiTestRoute: ApiTestRoute,
  ApiAdminCleanupNonUsJobsRoute: ApiAdminCleanupNonUsJobsRoute,
  ApiAdminSeedVectorsRoute: ApiAdminSeedVectorsRoute,
  ApiAiGenerateResumeRoute: ApiAiGenerateResumeRoute,
  ApiAiInsightsRoute: ApiAiInsightsRoute,
  ApiAiMatchRoute: ApiAiMatchRoute,
  ApiAiRecommendRoute: ApiAiRecommendRoute,
  ApiAiScoreAllRoute: ApiAiScoreAllRoute,
  ApiAiSearchRoute: ApiAiSearchRoute,
  ApiAiUnicornRoute: ApiAiUnicornRoute,
  ApiAuthGetSessionRoute: ApiAuthGetSessionRoute,
  ApiAuthSignOutRoute: ApiAuthSignOutRoute,
  ApiCrawlAtsRoute: ApiCrawlAtsRoute,
  ApiCrawlCronRoute: ApiCrawlCronRoute,
  ApiCrawlSaveBoardRoute: ApiCrawlSaveBoardRoute,
  ApiCrawlStatsRoute: ApiCrawlStatsRoute,
  ApiCrawlToggleBoardRoute: ApiCrawlToggleBoardRoute,
  ApiDiscoveryCronRoute: ApiDiscoveryCronRoute,
  ApiDiscoveryDeleteBoardRoute: ApiDiscoveryDeleteBoardRoute,
  ApiDiscoveryRunPhaseRoute: ApiDiscoveryRunPhaseRoute,
  ApiDiscoveryStatsRoute: ApiDiscoveryStatsRoute,
  ApiDiscoveryValidateBoardRoute: ApiDiscoveryValidateBoardRoute,
  ApiJobsCrawlerSearchRoute: ApiJobsCrawlerSearchRoute,
  ApiJobsSearchRoute: ApiJobsSearchRoute,
  ApiV3CategoriesRoute: ApiV3CategoriesRoute,
  ApiV3JobContentRoute: ApiV3JobContentRoute,
  ApiV3JobsRoute: ApiV3JobsRouteWithChildren,
  ApiV3LogsRoute: ApiV3LogsRoute,
  ApiV3StatsRoute: ApiV3StatsRoute,
  ApiAuthSignInEmailRoute: ApiAuthSignInEmailRoute,
  ApiAuthSignUpEmailRoute: ApiAuthSignUpEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
